apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: uv4zbx7ec-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:923d87840304e1086e092ee44bdb53e54ce9c03d@sha256:0ca69f6a22216fcc6640a4149afd2d5db05e58ea87dc0237fb68a6493edd856c
        name: container-image  
