apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uv4zbx7ec-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uv4zbx7ec-java-quarkus-gitops